{
  "generated_at": "2026-05-18T12:00:19.474281",
  "total": 6,
  "letters": [
    {
      "id": "OUT-001-0518-1",
      "date": "2026-05-18",
      "target_company": "Aus Modular Homes Pty Ltd",
      "website": "https://www.ausmodularhomes.com.au",
      "contact_email": "info@ausmodularhomes.com.au",
      "contact_name": "Michael Chen",
      "contact_title": "Procurement Director",
      "product": "钢结构房屋",
      "sender_company": "Zhejiang Fsilon Building Materials Co., Ltd.",
      "subject": "Light Steel Structure House - Aus Modular Homes Pty Ltd | 工厂直供澳洲市场",
      "body": "Subject: Light Steel Structure House - Aus Modular Homes Pty Ltd | 工厂直供澳洲市场\n\nHi Michael Chen,\n\nI'm writing from Zhejiang Fsilon Building Materials Co., Ltd., a leading Chinese manufacturer of 钢结构房屋 with ISO9001/CE certifications.\n\nWe noticed Aus Modular Homes Pty Ltd is active in the Australian prefabricated housing and modular construction space, and believe our products could be a strong fit for your portfolio:\n\n• 钢结构房屋: 热镀锌防腐、25年质保、可定制\n• MOQ: 20 units / 40ft container | Lead time: 15-20 working days\n• Competitive FOB pricing with exclusive territory protection\n• Samples available for evaluation\n\nWe're looking for a reliable distributor/importer in Australia. Would you be interested in exploring this opportunity?\n\nBest regards,\nZhejiang Fsilon Building Materials Co., Ltd.\ninfo@fsilon.com\n+86-573-87654321\nhttps://www.fsilon.com\n",
      "template_type": "distributor",
      "status": "pending_review"
    },
    {
      "id": "OUT-002-0518-2",
      "date": "2026-05-18",
      "target_company": "Melbourne Prefab Solutions",
      "website": "https://www.melbourneprefab.com.au",
      "contact_email": "sales@melbourneprefab.com.au",
      "contact_name": "Sarah Williams",
      "contact_title": "Operations Manager",
      "product": "集装箱房屋",
      "sender_company": "Shanghai Bangshan Modular Building Technology Co., Ltd.",
      "subject": "Partner with Us for Container House in Australia",
      "body": "Subject: Partner with Us for Container House in Australia\n\nHi Sarah Williams,\n\nShanghai Bangshan Modular Building Technology Co., Ltd. is a ['ISO9001', 'CE', 'BV'] manufacturer specializing in 集装箱房屋 for the Australian market.\n\nWe're reaching out because your company's project portfolio in prefabricated housing and modular construction aligns with our product strengths:\n\n• 即装即用、灵活扩容、可搬迁重复使用\n• Full technical documentation (Structural, Thermal, NCC compliance)\n• On-site installation support available\n• Previous project references in Australia\n\nWe're looking for experienced installation partners. Would you be open to a preliminary discussion?\n\nBest regards,\nShanghai Bangshan Modular Building Technology Co., Ltd.\nexport@bangshanmodular.com\n+86-21-58967532\nhttps://www.bangshanmodular.com\n",
      "template_type": "installer",
      "status": "pending_review"
    },
    {
      "id": "OUT-005-0518-3",
      "date": "2026-05-18",
      "target_company": "Apex Modular Construction (Queensland)",
      "website": "https://www.apexmodular.com.au",
      "contact_email": "info@apexmodular.com.au",
      "contact_name": "Tom Henderson",
      "contact_title": "Director of Operations",
      "product": "模块化建筑",
      "sender_company": "Guangdong Integrated Housing Co., Ltd.",
      "subject": "Partner with Us for Modular Building in Australia",
      "body": "Subject: Partner with Us for Modular Building in Australia\n\nHi Tom Henderson,\n\nGuangdong Integrated Housing Co., Ltd. is a ['ISO9001', 'CE', 'TUV'] manufacturer specializing in 模块化建筑 for the Australian market.\n\nWe're reaching out because your company's project portfolio in prefabricated housing and modular construction aligns with our product strengths:\n\n• 工厂预制80%、现场组装快、成本可控\n• Full technical documentation (Structural, Thermal, NCC compliance)\n• On-site installation support available\n• Previous project references in Australia\n\nWe're looking for experienced installation partners. Would you be open to a preliminary discussion?\n\nBest regards,\nGuangdong Integrated Housing Co., Ltd.\nsales@gdioh.com\n+86-20-87654321\nhttps://www.gdioh.com\n",
      "template_type": "installer",
      "status": "pending_review"
    },
    {
      "id": "OUT-006-0518-4",
      "date": "2026-05-18",
      "target_company": "Pacific Prefab Supplies",
      "website": "https://www.pacificprefab.com",
      "contact_email": "procurement@pacificprefab.com",
      "contact_name": "Angela Torres",
      "contact_title": "Procurement Manager",
      "product": "钢结构房屋",
      "sender_company": "Shanghai Bangshan Modular Building Technology Co., Ltd.",
      "subject": "Light Steel Structure House - Pacific Prefab Supplies | 工厂直供澳洲市场",
      "body": "Subject: Light Steel Structure House - Pacific Prefab Supplies | 工厂直供澳洲市场\n\nHi Angela Torres,\n\nI'm writing from Shanghai Bangshan Modular Building Technology Co., Ltd., a leading Chinese manufacturer of 钢结构房屋 with ISO9001/CE certifications.\n\nWe noticed Pacific Prefab Supplies is active in the Australian prefabricated housing and modular construction space, and believe our products could be a strong fit for your portfolio:\n\n• 钢结构房屋: 热镀锌防腐、25年质保、可定制\n• MOQ: 20 units / 40ft container | Lead time: 15-20 working days\n• Competitive FOB pricing with exclusive territory protection\n• Samples available for evaluation\n\nWe're looking for a reliable distributor/importer in Australia. Would you be interested in exploring this opportunity?\n\nBest regards,\nShanghai Bangshan Modular Building Technology Co., Ltd.\nexport@bangshanmodular.com\n+86-21-58967532\nhttps://www.bangshanmodular.com\n",
      "template_type": "distributor",
      "status": "pending_review"
    },
    {
      "id": "OUT-MFG-0518-5",
      "date": "2026-05-18",
      "target_company": "浙江法狮龙建材有限公司",
      "website": "https://www.fsilon.com",
      "contact_email": "info@fsilon.com",
      "contact_name": "Export Manager",
      "contact_title": "Export Department",
      "product": "折叠房屋",
      "sender_company": "SAYELF Trading",
      "subject": "Jewel of the Bride (吉达) - 折叠房屋 Supply Opportunity",
      "body": "Subject: Jewel of the Bride (吉达) - 折叠房屋 Supply Opportunity\n\nExport Manager 您好，\n\n我是 SAYELF Trading 的跨境业务对接人。近期获取到以下沙特项目采购需求，可能与贵司产品线高度匹配：\n\n项目：Jewel of the Bride (吉达)\n预算：$2B USD\n需求：折叠房屋（劳工营模块化住房，高峰期3万工人）\n状态：2026年5月启动，5-8年工期\n\n我方已建立该项目相关渠道，需要寻找具备以下条件的供应商：\n• 快速安装、模块化设计、抗震达标\n• 有中东出口经验\n• 可提供技术文档和合规认证\n\n如贵司有兴趣参与，请回复确认，我方将提供项目详细信息及对接方式。\n\n此致，\nSAYELF Trading\nsayelf.trading@gmail.com\n\n\n",
      "template_type": "factory_lead",
      "status": "pending_review"
    },
    {
      "id": "OUT-MFG-0518-6",
      "date": "2026-05-18",
      "target_company": "上海邦山模块化建筑科技有限公司",
      "website": "https://www.bangshanmodular.com",
      "contact_email": "export@bangshanmodular.com",
      "contact_name": "Export Director",
      "contact_title": "Export Department",
      "product": "模块化建筑",
      "sender_company": "SAYELF Trading",
      "subject": "NEOM THE LINE - 模块化建筑 Supply Opportunity",
      "body": "Subject: NEOM THE LINE - 模块化建筑 Supply Opportunity\n\nExport Director 您好，\n\n我是 SAYELF Trading 的跨境业务对接人。近期获取到以下沙特项目采购需求，可能与贵司产品线高度匹配：\n\n项目：NEOM THE LINE\n预算：$500B USD\n需求：模块化建筑（基建劳工营/钢结构/模块化建筑）\n状态：建设中，长期采购需求\n\n我方已建立该项目相关渠道，需要寻找具备以下条件的供应商：\n• 工厂预制80%、现场组装快、成本可控\n• 有中东出口经验\n• 可提供技术文档和合规认证\n\n如贵司有兴趣参与，请回复确认，我方将提供项目详细信息及对接方式。\n\n此致，\nSAYELF Trading\nsayelf.trading@gmail.com\n\n\n",
      "template_type": "factory_lead",
      "status": "pending_review"
    }
  ]
}