#!/home/sayelf/.local/venvs/scraper/bin/python3
"""Generate PDF buyer intel report from markdown source."""
import re
from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.cell(0, 5, "TAIYI - Buyer Intelligence Report", align="L")
            self.cell(0, 5, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 10, "Generated by Taiyi AI | 2026-05-07 | Confidential", align="C")

def make_pdf():
    pdf = PDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(220, 50, 50)
    pdf.cell(0, 15, "BUYER INTELLIGENCE REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, "Product-Matched Buyers | Middle East + Australia", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, "2026-05-07", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Section helper
    def section(title, color=(50, 50, 150)):
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*color)
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(*color)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

    def bullet(text, bold_prefix=""):
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(30, 30, 30)
        # Use a table-like approach for safety
        pdf.set_x(15)
        if bold_prefix:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 5, bold_prefix + text, new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.multi_cell(180, 5, text)

    # =========== LABOR CAMP ===========
    section("1. LABOR CAMP - HIGHEST DEMAND")
    buyers_labor = [
        ("Jewel of the Bride (Jeddah)", "SAUDI ARABIA", "$2B", "2026.5 Launch", "P0", "30K peak workers"),
        ("NEOM THE LINE", "SAUDI ARABIA", "$500B+", "Under Construction", "P0", "World's largest project"),
        ("Trojena Dam (NEOM)", "SAUDI ARABIA", "SAR 658M", "Awarded", "P0", "Webuild contractor"),
        ("Red Sea Project", "SAUDI ARABIA", "-", "Under Construction", "P1", "Luxury camps"),
        ("Saadiyat Road Project", "UAE/ABU DHABI", "$2.9B", "Ongoing", "P1", "Infrastructure"),
        ("Dubai 2040 Plan", "UAE/DUBAI", "Long-term", "Through 2040", "P1", "Multi-zone"),
        ("Iraq 21 New Cities", "IRAQ", "3M housing gap", "Planning", "P1", "Modular optimal"),
    ]
    # Table header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(230, 230, 240)
    pdf.cell(50, 7, "Project / Buyer", border=1, fill=True, align="C")
    pdf.cell(20, 7, "Region", border=1, fill=True, align="C")
    pdf.cell(20, 7, "Budget", border=1, fill=True, align="C")
    pdf.cell(25, 7, "Status", border=1, fill=True, align="C")
    pdf.cell(12, 7, "Pri.", border=1, fill=True, align="C")
    pdf.cell(53, 7, "Note", border=1, fill=True, align="C", new_x="LMARGIN", new_y="NEXT")
    
    for name, region, budget, status, pri, note in buyers_labor:
        pdf.set_font("Helvetica", "", 7.5)
        h = 6
        pdf.cell(50, h, name[:32], border=1)
        pdf.cell(20, h, region, border=1, align="C")
        pdf.cell(20, h, budget, border=1, align="C")
        pdf.cell(25, h, status, border=1, align="C")
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(12, h, pri, border=1, align="C")
        pdf.set_font("Helvetica", "", 7.5)
        pdf.cell(53, h, note[:35], border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(3)
    bullet("Key labor camp suppliers in KSA: Red Sea Intl (RSI), Webuild, Dorce Prefab, Mokamela, Ebn Al Arab")

    # =========== STEEL STRUCTURE ===========
    section("2. STEEL STRUCTURE - SUSTAINED DEMAND")
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(230, 230, 240)
    pdf.cell(50, 7, "Project / Buyer", border=1, fill=True, align="C")
    pdf.cell(20, 7, "Region", border=1, fill=True, align="C")
    pdf.cell(20, 7, "Budget", border=1, fill=True, align="C")
    pdf.cell(25, 7, "Status", border=1, fill=True, align="C")
    pdf.cell(12, 7, "Pri.", border=1, fill=True, align="C")
    pdf.cell(53, 7, "Note", border=1, fill=True, align="C", new_x="LMARGIN", new_y="NEXT")
    
    steel_buyers = [
        ("Jewel of the Bride", "SAUDI ARABIA", "$2B", "2026.5 Launch", "P0", "93-layer tower"),
        ("NEOM THE LINE", "SAUDI ARABIA", "$500B+", "Under Construction", "P0", "Linear city"),
        ("H&H City Tower (93fl)", "SAUDI ARABIA", "-", "2026.5 Launch", "P0", "Mixed-use"),
        ("Red Sea Project", "SAUDI ARABIA", "-", "Under Construction", "P1", "Resort+infra"),
        ("Dubai 2040 Plan", "UAE/DUBAI", "Long-term", "Through 2040", "P1", "Multi-zone"),
        ("Iraq 21 New Cities", "IRAQ", "3M homes", "Planning", "P1", "Nationwide"),
    ]
    for name, region, budget, status, pri, note in steel_buyers:
        pdf.set_font("Helvetica", "", 7.5)
        h = 6
        pdf.cell(50, h, name[:32], border=1)
        pdf.cell(20, h, region, border=1, align="C")
        pdf.cell(20, h, budget, border=1, align="C")
        pdf.cell(25, h, status, border=1, align="C")
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(12, h, pri, border=1, align="C")
        pdf.set_font("Helvetica", "", 7.5)
        pdf.cell(53, h, note[:35], border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(3)
    bullet("Verified steel companies (buyers/partners):")
    bullet("  Afco Steel - Jeddah | info@afcosteel.com.sa | +966-12-636-9088 (5/5 verified)", bold_prefix="")
    bullet("  SBS Contracting - KSA | info@sbs-contracting.com | +966-54-898-6765", bold_prefix="")
    bullet("  Zamil Steel - Dammam | World's largest PEB factory | 45+ years", bold_prefix="")

    # =========== MODULAR ===========
    section("3. MODULAR BUILDING - GROWTH SEGMENT")
    pdf.set_font("Helvetica", "", 10)
    mod_buyers = [
        ("NEOM THE LINE", "SAUDI ARABIA", "$500B+", "P0"),
        ("Red Sea Project (Luxury Camps)", "SAUDI ARABIA", "-", "P1"),
        ("Dubai 2040 Plan", "UAE/DUBAI", "Long-term", "P1"),
        ("Iraq 21 New Cities", "IRAQ", "3M homes", "P1"),
    ]
    for name, region, budget, pri in mod_buyers:
        bullet(f"  {name} | {region} | {budget} | {pri}", bold_prefix="")

    # =========== AUSTRALIA ===========
    section("4. AUSTRALIA MARKET OPPORTUNITY")
    pdf.set_font("Helvetica", "", 10)
    bullet("Market size: USD 11.3B (modular construction)")
    bullet("Housing gap: 200K-300K units")
    bullet("Drivers: housing shortage, labor cost, sustainability")
    bullet("Key resources:")
    bullet("  prefabAUS member dir: prefabaus.org.au/member-directory/")
    bullet("  Australian tenders: australiantenders.com.au")
    bullet("  Modular co. top 100: ensun.io/search/modular-building/australia")

    # =========== OUTREACH STATUS ===========
    pdf.add_page()
    section("5. OUTREACH STATUS")
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(230, 230, 240)
    pdf.cell(50, 7, "Buyer Lead", border=1, fill=True)
    pdf.cell(50, 7, "Factory Contacted", border=1, fill=True)
    pdf.cell(20, 7, "Method", border=1, fill=True)
    pdf.cell(20, 7, "Response", border=1, fill=True)
    pdf.cell(40, 7, "Status", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    
    outreach = [
        ("Jewel of the Bride", "Guangdong Integrated Housing", "Email", "Pending", "Following up"),
        ("Jewel of the Bride", "Fashilong Building Materials", "Email", "Pending", "Following up"),
        ("NEOM Labor Camp", "Guangdong Integrated Housing", "Email", "Pending", "Following up"),
    ]
    for lead, factory, method, resp, status in outreach:
        pdf.set_font("Helvetica", "", 8)
        h = 6
        pdf.cell(50, h, lead, border=1)
        pdf.cell(50, h, factory, border=1)
        pdf.cell(20, h, method, border=1, align="C")
        pdf.cell(20, h, resp, border=1, align="C")
        pdf.cell(40, h, status, border=1, new_x="LMARGIN", new_y="NEXT")

    # =========== NEW LEADS ===========
    pdf.ln(5)
    section("6. NEW LEADS (TO VERIFY)")
    pdf.set_font("Helvetica", "", 10)
    new_leads = [
        "Red Sea Intl (RSI) - KSA modular camp leader, won SAR 658M Trojena contract",
        "Webuild - Italian EPC for Trojena Dam labor camp",
        "Dorce Prefabricated - Turkish camp solutions in KSA",
        "Mokamela Prefab - Jeddah-based prefab/camp builder",
        "Base Fixed Contracting Co. - KSA portable cabin manufacturer (6+ yrs)",
        "Aldamegh Portable House Factory - KSA prefab manufacturer",
        "MS Metals (Al Raeel Group) - KSA/GCC prefab + steel since 2007",
        "SASP - KSA portable cabin supplier",
    ]
    for lead in new_leads:
        bullet(f"- {lead}")

    # =========== TENDER PLATFORMS ===========
    pdf.ln(3)
    section("7. TENDER PLATFORMS (MONITOR)")
    pdf.set_font("Helvetica", "", 9)
    platforms = [
        ("Construction Week Online", "Middle East", "constructionweekonline.com/projects-tenders"),
        ("KSA Tenders Gate", "Saudi Arabia", "ksatendersgate.com"),
        ("TenderSA", "Saudi Arabia", "tendersa.com"),
        ("Etimad.sa", "Saudi Arabia", "etimad.sa (gov procurement)"),
        ("Iraq Housing Ministry", "Iraq", "alaskan.moch.gov.iq"),
        ("UNGM Iraq", "Iraq", "ungm.org"),
        ("Australian Tenders", "Australia", "australiantenders.com.au"),
        ("prefabAUS", "Australia", "prefabaus.org.au"),
    ]
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(230, 230, 240)
    pdf.cell(50, 7, "Platform", border=1, fill=True)
    pdf.cell(40, 7, "Region", border=1, fill=True)
    pdf.cell(90, 7, "URL", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    for name, region, url in platforms:
        pdf.set_font("Helvetica", "", 7.5)
        h = 6
        pdf.cell(50, h, name, border=1)
        pdf.cell(40, h, region, border=1)
        pdf.cell(90, h, url, border=1, new_x="LMARGIN", new_y="NEXT")

    # =========== ACTION PLAN ===========
    pdf.add_page()
    section("8. RECOMMENDED ACTIONS")
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(200, 50, 50)
    pdf.cell(0, 7, "THIS WEEK:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    bullet("Contact Afco Steel (verified) - negotiate steel structure cooperation")
    bullet("Contact SBS Contracting (verified) - pitch buyer intel subscription")
    bullet("Monitor Jewel of the Bride latest tender news")
    
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(50, 50, 150)
    pdf.cell(0, 7, "THIS MONTH:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    bullet("Verify RSI / Webuild procurement contacts")
    bullet("Register on Etimad.sa for live Saudi tenders")
    bullet("Subscribe to prefabAUS directory for Australian intel")
    bullet("Subscribe to Iraq Housing Ministry tenders")

    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 7, "LONG-TERM:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    bullet("Automate project radar (Etimad.sa -> buyer-intel DB)")
    bullet("Build factory Telegram push system")
    bullet("Launch subscription billing")

    # =========== CONFIDENCE ===========
    pdf.ln(5)
    section("9. CONFIDENCE ASSESSMENT")
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(230, 230, 240)
    pdf.cell(55, 7, "Buyer", border=1, fill=True)
    pdf.cell(25, 7, "Verification", border=1, fill=True)
    pdf.cell(35, 7, "Contact", border=1, fill=True)
    pdf.cell(25, 7, "Priority", border=1, fill=True)
    pdf.cell(40, 7, "Next Step", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    
    confidence = [
        ("Jewel of the Bride", "Public source", "-", "P0", "Monitor tenders"),
        ("NEOM THE LINE", "Public source", "-", "P0", "Track procurement"),
        ("Afco Steel", "5/5 verified", "Email/Phone", "P1-Coop", "Reach out"),
        ("SBS Contracting", "Verified", "Email/Phone", "P1", "Pitch subscr."),
        ("Zamil Steel", "Verified", "Web form", "P1", "Register"),
        ("SAW Constructions (AU)", "Verified", "4x Email", "P1", "Contact"),
    ]
    for name, verif, contact, pri, nxt in confidence:
        pdf.set_font("Helvetica", "", 8)
        h = 6
        pdf.cell(55, h, name, border=1)
        pdf.cell(25, h, verif, border=1, align="C")
        pdf.cell(35, h, contact, border=1, align="C")
        pdf.cell(25, h, pri, border=1, align="C")
        pdf.cell(40, h, nxt, border=1, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "TAIYI Buyer Intelligence Engine | Generated 2026-05-07 12:40 CST", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.output("/home/sayelf/.openclaw/workspace/reports/buyer-intel-report-20260507.pdf")
    print("PDF generated: reports/buyer-intel-report-20260507.pdf")

if __name__ == "__main__":
    make_pdf()
